### ISSUE TITLE
Create Users class

### ISSUE THREAD

**Issue by mitander** [BulboBaggins/Bulbo#24]
Create a class that holds information about Users.

username
email
uuid
pass
date

Should be created under Models folder.

**Comment by cur1ousss** [comment]
` import java.util.Date;
import java.util.UUID;

public class Users{
    public String user_name;
    protected String email;
    private UUID uuid;
    private String pass;
    public Date date;
    
    public void setUserName(String user_name){
        this.user_name=user_name;
    }

    public void setEmail(String email){
        this.email=email;
    }

    public void setUUID(UUID uuid){
        this.uuid=uuid;
    }

    public void setPass(String pass){
        this.pass=pass;
    }

    public void setDate(Date date){
        this.date=date;
    }


} `

Is this fine syntax?

**Comment by mitander** [comment]
Hey cybrpnkkrtos.

Thanks for your contribution, but there is a pull request for this issue up. 
This issue will now be closed.
